### ISSUE TITLE
Thankyou so much!

### ISSUE THREAD

**Issue by ryantheleach** [misode/brigadier-ts#1]
I was just thinking about porting Brig to ts, you absolute legend.

How close is this to complete?

**Comment by misode** [comment]
Most of the features are done, and I'm currently working on the suggestions. I'm also not completely sure how to handle argument types like longs and doubles since these are all represented by `number` in TypeScript, so feel free to give feedback about the decisions I've made so far.

**Comment by ryantheleach** [comment]
Personally, I'd attempt to make sure they work as Java does, and (in addition) create 'number' types as well.

That way people who are using it to validate existing MC stuff can do so, and anyone using it as a 'familiar friend' after working with in in Java, can use something that feels a little more TS/JS native for their projects.

**Comment by ryantheleach** [comment]
For what it's worth, I'm tempted to try to port some of the utilities in https://github.com/lucko/commodore to Brig-ts

**Comment by misode** [comment]
@ryantheleach I'm not too familiar with that utility. What features specifically are worth having that are not in Mojang/brigadier?

**Comment by ryantheleach** [comment]
I wouldn't put them in brig-ts directly, but having a text form / parser that works on both java and ts? That would be pretty powerful. I think the rest of the features are minimal, and unable to be ported due to dependencies of MC/Bukkit.

See the section labelled `Using commodore's .commodore file format` https://github.com/lucko/commodore/blob/master/README.md

**Comment by misode** [comment]
@ryantheleach I had a look at the commodore format, but it confuses me a little. While it does show the structure of the command tree very nicely, where are you supposed to define to code to run at each node? When you define the structure in code, you use lambdas.

The same is the case with the [command registry](https://github.com/Arcensoth/mcdata/blob/master/generated/reports/commands.json) from vanilla. It only has `"executable": true`.

**Comment by ryantheleach** [comment]
@misode I havn't had a chance to play with it in earnest, I've only just managed to setup a (rough) tests setup. I'll let you know when I have more. (https://github.com/ryantheleach/brigadier-ts/tree/tests) Don't pull this yet, but feel free to check it out, / tell me if I'm doing something that rubs you the wrong way. I expect it will be a PR in due course. I just want to cleanup some of the packages first, and expect I'll be force-pushing to that branch until I get it right.
