### ISSUE TITLE
Big integer argument types should be available

### ISSUE THREAD

**Issue by haykam821** [misode/brigadier-ts#7]
Right now, [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) cannot be expressed through one of the existing argument type short of manually parsing it from a string.

**Comment by misode** [comment]
I'm not sure if I want to include this in the package, since [support for `BigInt`](https://caniuse.com/bigint) is not the best yet. Would it be acceptable to create this  `ArgumentType` yourself?

**Comment by haykam821** [comment]
Would it make sense to have a separate package dedicated to bleeding-edge or less common types? I can easily create an argument type myself but I would rather not have to maintain a package to share the argument type across projects.

**Comment by misode** [comment]
I presume there probably isn't a project that uses this with old browsers as a requirement, so it should be fine to add this.
